import { Anime, ContentType, User } from "./types";

export const MOCK_ANIME_CATALOG: Anime[] = [
  {
    id: '1',
    title: 'Solo Leveling',
    japaneseTitle: 'Ore dake Level Up na Ken',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-61m8996N7v8n.png',
    bannerImage: '/assets/hero-solo-leveling.png',
    description: 'In a world where hunters, humans who possess magical abilities, must battle deadly monsters to protect mankind from certain annihilation, a notoriously weak hunter named Sung Jinwoo finds himself in a seemingly endless struggle for survival.',
    rating: 9.1,
    genres: ['Action', 'Adventure', 'Fantasy'],
    year: 2024,
    status: 'Ongoing',
    type: 'TV',
    quality: '4K',
    totalEpisodes: 12,
    currentEpisode: 12,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English', 'Hindi'],
    watchOrder: [
      { id: '1-1', type: ContentType.EPISODE, title: 'I\u0027m Used to It', duration: '24m', orderIndex: 1, isReleased: true, thumbnail: 'https://picsum.photos/seed/sl1/300/170', description: 'Jinwoo and his party enter a double dungeon.' },
      { id: '1-2', type: ContentType.EPISODE, title: 'If I Had One More Chance', duration: '24m', orderIndex: 2, isReleased: true, thumbnail: 'https://picsum.photos/seed/sl2/300/170', description: 'The struggle continues in the hidden boss room.' }
    ]
  },
  {
    id: '2',
    title: 'One Piece',
    japaneseTitle: 'Wan Pīsu',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx21-6O9iDR9yvM0v.jpg',
    bannerImage: '/assets/hero-one-piece.png',
    description: 'Gol D. Roger was known as the "Pirate King," the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world.',
    rating: 9.5,
    genres: ['Action', 'Adventure', 'Comedy'],
    year: 1999,
    status: 'Ongoing',
    type: 'TV',
    quality: 'FHD',
    totalEpisodes: 1100,
    currentEpisode: 1098,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: [
      { id: '2-1', type: ContentType.EPISODE, title: 'I\u0027m Luffy! The Man Who\u0027ll Become the Pirate King!', duration: '24m', orderIndex: 1, isReleased: true, thumbnail: 'https://picsum.photos/seed/op1/300/170', description: 'A young boy sets out on a journey.' },
      { id: '2-2', type: ContentType.EPISODE, title: 'Enter the Great Swordsman! Pirate Hunter Roronoa Zoro!', duration: '24m', orderIndex: 2, isReleased: true, thumbnail: 'https://picsum.photos/seed/op2/300/170', description: 'Luffy meets his first crewmate.' }
    ]
  },
  {
    id: '3',
    title: 'Jujutsu Kaisen Season 2',
    japaneseTitle: 'Jujutsu Kaisen',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx145064-9P4S260SND44.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/145064-9P4S260SND44.jpg',
    description: 'The past comes back to haunt Satoru Gojo as he recalls his days at Jujutsu High with Suguru Geto. Meanwhile, in the present, a massive cursed spirit threat looms over Shibuya.',
    rating: 9.3,
    genres: ['Action', 'Supernatural'],
    year: 2023,
    status: 'Completed',
    type: 'TV',
    quality: '4K',
    totalEpisodes: 23,
    currentEpisode: 23,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '4',
    title: 'Frieren: Beyond Journey\u0027s End',
    japaneseTitle: 'Sousou no Frieren',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154587-Y9FfE7N9f7N9.png',
    bannerImage: '/assets/hero-frieren.png',
    description: 'The mage Frieren and her fellow adventurers have defeated the Demon King and brought peace to the land. But Frieren, being an elf, will outlive the rest of her party.',
    rating: 9.6,
    genres: ['Adventure', 'Drama', 'Fantasy'],
    year: 2023,
    status: 'Completed',
    type: 'TV',
    quality: '4K',
    totalEpisodes: 28,
    currentEpisode: 28,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: [
      { id: '4-1', type: ContentType.EPISODE, title: 'The Journey\u0027s End', duration: '24m', orderIndex: 1, isReleased: true, thumbnail: 'https://picsum.photos/seed/fr1/300/170', description: 'The heroes return from their quest.' },
      { id: '4-2', type: ContentType.EPISODE, title: 'It Didn\u0027t Have to Be Magic', duration: '24m', orderIndex: 2, isReleased: true, thumbnail: 'https://picsum.photos/seed/fr2/300/170', description: 'Frieren begins her new journey.' }
    ]
  },
  {
    id: '5',
    title: 'Demon Slayer: Kimetsu no Yaiba',
    japaneseTitle: 'Kimetsu no Yaiba',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-WGoFeGZp9t7X.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/101922-WGoFeGZp9t7X.jpg',
    description: 'Tanjiro Kamado, a young boy whose family is killed by a demon, joins the Demon Slayer Corps to find a way to turn his sister back into a human.',
    rating: 9.1,
    genres: ['Action', 'Fantasy'],
    year: 2019,
    status: 'Ongoing',
    type: 'TV',
    quality: '4K',
    totalEpisodes: 55,
    currentEpisode: 55,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '6',
    title: 'Attack on Titan: The Final Season',
    japaneseTitle: 'Shingeki no Kyojin: The Final Season',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx110277-h9Ipx9N9v7N9.png',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/110277-h9Ipx9N9v7N9.jpg',
    description: 'The truth about the world outside the walls is revealed, and the battle for survival takes a dramatic and dark turn.',
    rating: 9.4,
    genres: ['Action', 'Drama', 'Mystery'],
    year: 2020,
    status: 'Completed',
    type: 'TV',
    quality: 'FHD',
    totalEpisodes: 30,
    currentEpisode: 30,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '7',
    title: 'Chainsaw Man',
    japaneseTitle: 'Chainsaw Man',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx127230-FlyX9v7N9f7N.png',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/127230-FlyX9v7N9f7N.jpg',
    description: 'Denji is a young man struggling to pay off his father\u0027s debt to the yakuza. He works as a devil hunter with his devil-dog, Pochita.',
    rating: 8.9,
    genres: ['Action', 'Comedy', 'Horror'],
    year: 2022,
    status: 'Completed',
    type: 'TV',
    quality: '4K',
    totalEpisodes: 12,
    currentEpisode: 12,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '8',
    title: 'Mashle: Magic and Muscles',
    japaneseTitle: 'Mashle',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151801-9P4S260SND44.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/151801-9P4S260SND44.jpg',
    description: 'In a world where magic is everything, Mash Burnedead has no magic but tons of muscle. He joins a magic academy to prove that strength can beat magic.',
    rating: 8.5,
    genres: ['Action', 'Comedy', 'Fantasy'],
    year: 2023,
    status: 'Ongoing',
    type: 'TV',
    quality: 'FHD',
    totalEpisodes: 24,
    currentEpisode: 24,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '9',
    title: 'Spy x Family',
    japaneseTitle: 'Spy x Family',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx140960-Y9FfE7N9f7N9.png',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/140960-Y9FfE7N9f7N9.jpg',
    description: 'To maintain peace between rival nations, a spy must build a "family" as a cover. However, his wife is an assassin and his daughter is a telepath.',
    rating: 8.8,
    genres: ['Action', 'Comedy'],
    year: 2022,
    status: 'Completed',
    type: 'TV',
    quality: 'FHD',
    totalEpisodes: 25,
    currentEpisode: 25,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '10',
    title: 'Blue Lock',
    japaneseTitle: 'Blue Lock',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx137833-WGoFeGZp9t7X.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/137833-WGoFeGZp9t7X.jpg',
    description: 'Japan\u0027s desire for World Cup glory leads the Japanese Football Federation to launch a new rigorous training program to find the national team\u0027s next striker.',
    rating: 8.7,
    genres: ['Sports'],
    year: 2022,
    status: 'Ongoing',
    type: 'TV',
    quality: '4K',
    totalEpisodes: 24,
    currentEpisode: 24,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '11',
    title: 'Hell\u0027s Paradise',
    japaneseTitle: 'Jigokuraku',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx128893-h9Ipx9N9v7N9.png',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/128893-h9Ipx9N9v7N9.jpg',
    description: 'Gabimaru the Hollow, a ninja from Iwagakure Village, is sentenced to death. However, he is given a chance to be pardoned if he can find the Elixir of Life on a mysterious island.',
    rating: 8.6,
    genres: ['Action', 'Adventure', 'Supernatural'],
    year: 2023,
    status: 'Completed',
    type: 'TV',
    quality: 'FHD',
    totalEpisodes: 13,
    currentEpisode: 13,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '12',
    title: 'Oshi no Ko',
    japaneseTitle: 'Oshi no Ko',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx150672-FlyX9v7N9f7N.png',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/150672-FlyX9v7N9f7N.jpg',
    description: 'A doctor and his deceased patient are reborn as the children of their favorite idol, Ai Hoshino. They navigate the dark side of the entertainment industry.',
    rating: 9.0,
    genres: ['Drama', 'Mystery', 'Supernatural'],
    year: 2023,
    status: 'Ongoing',
    type: 'TV',
    quality: '4K',
    totalEpisodes: 11,
    currentEpisode: 11,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '13',
    title: 'Vinland Saga Season 2',
    japaneseTitle: 'Vinland Saga',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx136430-9P4S260SND44.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/136430-9P4S260SND44.jpg',
    description: 'Thorfinn, now a slave in Denmark, seeks a new purpose in life after the death of his sworn enemy and father-figure.',
    rating: 9.2,
    genres: ['Action', 'Adventure', 'Drama'],
    year: 2023,
    status: 'Completed',
    type: 'TV',
    quality: '4K',
    totalEpisodes: 24,
    currentEpisode: 24,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '14',
    title: 'Bleach: Thousand-Year Blood War',
    japaneseTitle: 'Bleach: Sennen Kessen-hen',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx114446-Y9FfE7N9f7N9.png',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/114446-Y9FfE7N9f7N9.jpg',
    description: 'The Soul Society is under attack by the Wandenreich, a group of Quincies who were thought to have been wiped out 1,000 years ago.',
    rating: 9.4,
    genres: ['Action', 'Supernatural'],
    year: 2022,
    status: 'Ongoing',
    type: 'TV',
    quality: '4K',
    totalEpisodes: 26,
    currentEpisode: 26,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '15',
    title: 'The Eminence in Shadow',
    japaneseTitle: 'Kage no Jitsuryokusha ni Naritakute!',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx129193-WGoFeGZp9t7X.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/129193-WGoFeGZp9t7X.jpg',
    description: 'Cid Kagenou is reincarnated into a magical world and decides to become the "mastermind in the shadows" he always dreamed of being.',
    rating: 8.4,
    genres: ['Action', 'Comedy', 'Fantasy'],
    year: 2022,
    status: 'Completed',
    type: 'TV',
    quality: 'FHD',
    totalEpisodes: 20,
    currentEpisode: 20,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '16',
    title: 'Hunter x Hunter (2011)',
    japaneseTitle: 'Hunter x Hunter',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-o966vEiDP9S6.png',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/11061-o966vEiDP9S6.jpg',
    description: 'Gon Freecss aspires to become a Hunter, an exceptional being capable of greatness. With his friends and his potential, he seeks out his father.',
    rating: 9.6,
    genres: ['Action', 'Adventure', 'Fantasy'],
    year: 2011,
    status: 'Completed',
    type: 'TV',
    quality: 'FHD',
    totalEpisodes: 148,
    currentEpisode: 148,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '17',
    title: 'Mob Psycho 100 III',
    japaneseTitle: 'Mob Psycho 100',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx140671-DFfX9f7N9f7N.png',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/140671-DFfX9f7N9f7N.jpg',
    description: 'Shigeo "Mob" Kageyama is an average middle school boy, called Mob because he lacks a sense of presence. Despite his inconspicuousness, he possesses immense psychic power.',
    rating: 9.3,
    genres: ['Action', 'Comedy', 'Supernatural'],
    year: 2022,
    status: 'Completed',
    type: 'TV',
    quality: '4K',
    totalEpisodes: 12,
    currentEpisode: 12,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '18',
    title: 'Dr. STONE',
    japaneseTitle: 'Dr. STONE',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx105333-WGoFeGZp9t7X.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/105333-WGoFeGZp9t7X.jpg',
    description: 'After five years of harboring unspoken feelings, high-schooler Taiju Ooki is finally ready to confess his love to Yuzuriha Ogawa. Just when Taiju begins his confession, a blinding green light strikes the Earth and petrifies mankind around the world.',
    rating: 8.8,
    genres: ['Adventure', 'Sci-Fi'],
    year: 2019,
    status: 'Ongoing',
    type: 'TV',
    quality: 'FHD',
    totalEpisodes: 35,
    currentEpisode: 35,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '19',
    title: 'My Hero Academia Season 6',
    japaneseTitle: 'Boku no Hero Academia',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx138883-9P4S260SND44.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/138883-9P4S260SND44.jpg',
    description: 'The Paranormal Liberation War begins as the heroes launch a full-scale assault on the villains.',
    rating: 8.6,
    genres: ['Action', 'Comedy'],
    year: 2022,
    status: 'Completed',
    type: 'TV',
    quality: '4K',
    totalEpisodes: 25,
    currentEpisode: 25,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '21',
    title: 'Jack-of-All-Trades, Party of None',
    japaneseTitle: 'Benriya Saitou-san, Isekai ni Iku',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx144092-2v9fE7N9f7N9.png',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/144092-2v9fE7N9f7N9.jpg',
    description: 'Saitou is an ordinary handyman who gets transported to another world. He forms a party with a strong warrior, a powerful mage, and a greedy pixie.',
    rating: 8.2,
    genres: ['Adventure', 'Comedy', 'Fantasy'],
    year: 2023,
    status: 'Completed',
    type: 'TV',
    quality: 'FHD',
    totalEpisodes: 12,
    currentEpisode: 12,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '22',
    title: 'Hell\u0027s Paradise Season 2',
    japaneseTitle: 'Jigokuraku 2nd Season',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx164746-h9Ipx9N9v7N9.png',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/164746-h9Ipx9N9v7N9.jpg',
    description: 'The search for the Elixir of Life continues as more executioners and criminals land on the mysterious island.',
    rating: 8.8,
    genres: ['Action', 'Adventure', 'Supernatural'],
    year: 2025,
    status: 'Upcoming',
    type: 'TV',
    quality: '4K',
    totalEpisodes: 12,
    currentEpisode: 0,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  },
  {
    id: '23',
    title: 'Sentenced to Be a Hero',
    japaneseTitle: 'Isura',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx162812-FlyX9v7N9f7N.png',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/162812-FlyX9v7N9f7N.jpg',
    description: 'Convicts are forced into military service to fight the Demon Lord as "Heroes".',
    rating: 7.9,
    genres: ['Action', 'Fantasy'],
    year: 2024,
    status: 'Ongoing',
    type: 'TV',
    quality: 'FHD',
    totalEpisodes: 12,
    currentEpisode: 4,
    hasDub: true,
    hasSub: true,
    availableLanguages: ['Japanese', 'English'],
    watchOrder: []
  }
];


export const MOCK_USER: User = {
  id: 'u1',
  name: 'OtakuKing',
  email: 'king@aniflow.com',
  avatar: 'https://picsum.photos/100/100?random=999',
  role: 'user',
  isGuest: false,
  watchlist: ['2', '3'],
  history: ['1']
};